export const TASK_LOADED = 'taskLoaded'
export const TASK_ADDED = 'taskAdded'
export const TASK_DELETED = 'taskDeleted'
export const TASK_EDITED = 'taskEdited'
export const ADMIN_LOGIN = 'adminLogin'
export const USER_LOGIN = 'userLogin'
